####     _     _             _ _
##      | |   (_)           (_) |
##      | |    _  __ _ _   _ _| |__   __ _ ___  ___
##      | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \
##      | |___| | (_| | |_| | | |_) | (_| \__ \  __/
##      \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|
##                  | |
##                  |_|
##
##      The liquibase.properties file stores properties which do not change often,
##      such as database connection information. Properties stored here save time
##      and reduce risk of mistyped command line arguments.
##      Learn more: https://docs.liquibase.com/concepts/connections/creating-config-properties.html
####
####
##   Note about relative and absolute paths:
##      The liquibase.properties file requires paths for some properties.
##      The classpath is the path/to/resources (ex. src/main/resources).
##      The changeLogFile path is relative to the classpath.
##      The url H2 example below is relative to 'pwd' resource.
####

# Changelog file
changeLogFile=cat-changelog.xml

# Target database
liquibase.command.url=jdbc:postgresql://192.168.43.23:5432/cats
liquibase.command.username=postgres
liquibase.command.password=temaru00

# Reference database
liquibase.command.referenceUrl=jdbc:postgresql://192.168.43.23:5432/cats_dev
liquibase.command.referenceUsername=postgres
liquibase.command.referencePassword=temaru00

# Schema(s) to use
liquibase.command.schemas=cats
liquibase.command.referenceSchemas=cats

# Search path
liquibase.searchPath=/Users/macbookpro/Documents/RIANASCORP/FIANARANA/coding/Researches/rianajava/SimpleRun/src/main/resources/db

# Logging Configuration
# logLevel controls the amount of logging information generated. If not set, the default logLevel is INFO.
# Valid values, from least amount of logging to most, are:
#   OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# If you are having problems, setting the logLevel to DEBUG and re-running the command can be helpful.
# logLevel: DEBUG

# The logFile property controls where logging messages are sent. If this is not set, then logging messages are
# displayed on the console. If this is set, then messages will be sent to a file with the given name.
# logFile: liquibase.log

#### Liquibase Pro Key Information ####
# Learn more, contact support, or get or renew a Pro Key at https://www.liquibase.com/trial
# liquibase.licenseKey:

##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Get support at liquibase.com/support         ##
